### ISSUE TITLE
When selecting the Capitalize option, more text out of nowhere appears in the preview.

### ISSUE THREAD

**Issue by burhanharoon** [Textify-22/Textify#3]
So, there is a bug in the website. Whenever we click on the capitalize button, the written text is repeated many times. 

**Screenshot**:
![image](https://user-images.githubusercontent.com/89704304/195973351-54a56913-1923-4bf5-bdeb-203cb869fcf1.png)

**Comment by Mitushi-23** [comment]
> So, there is a bug in the website. Whenever we click on the capitalize button, the written text is repeated many times.
> 
> **Screenshot**: ![image](https://user-images.githubusercontent.com/89704304/195973351-54a56913-1923-4bf5-bdeb-203cb869fcf1.png)

**Comment by burhanharoon** [comment]
Assign this to me. I would to work on this!

**Comment by Mitushi-23** [comment]
ok I am assigning this to you.

**Comment by burhanharoon** [comment]
Got it and one more thing can you please add the `hacktoberfest-accepted` label too?

**Comment by Mitushi-23** [comment]
> Got it and one more thing can you please add the `hacktoberfest-accepted` label too?

on merging your PR I will add the label.

**Comment by burhanharoon** [comment]
Sure!

**Comment by burhanharoon** [comment]
@Mitushi-23 I have fixed the issue. Please have a look at it. Cheers!
