### ISSUE TITLE
Bug in words count and minutes Read.

### ISSUE THREAD

**Issue by Mitushi-23** [Textify-22/Textify#8]
No increase in words count and minutes read.

**Comment by bhattabhi013** [comment]
Hi @Mitushi-23,
I'll like to work on this.

**Comment by RuthChisom** [comment]
Hello, I'd love to work on this. Kindly assign this to me. Thanks.

**Comment by Mitushi-23** [comment]
ok I am assigning to both.

**Comment by Mitushi-23** [comment]
@RuthChisom @bhattabhi013 this issue is resolved, so you can try to work on other issue.
